apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-czra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-czra
    app.kubernetes.io/part-of: load-app-8693e747-7f4f-490f-aabd-94371a9199cb
  name: devfile-sample-czra
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-czra
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-czra
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-23-tenant/load-app-8693e747-7f4f-490f-aabd-94371a9199cb/devfile-sample-czra@sha256:c7dc1cc7a9b6b5b1129f46ab0bb3b79f4c08a6cb76ef450267c121494f77cb1f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
