apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-czra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-czra
    app.kubernetes.io/part-of: load-app-8693e747-7f4f-490f-aabd-94371a9199cb
  name: devfile-sample-czra
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-czra
status:
  loadBalancer: {}
