apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-czra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-czra
    app.kubernetes.io/part-of: load-app-8693e747-7f4f-490f-aabd-94371a9199cb
  name: devfile-sample-czragspy
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-czra
    weight: null
status: {}
